### ISSUE TITLE
Проблема с AJAX добавлением в корзину

### ISSUE THREAD

**Issue by apavliukov** [systemo-biz/wpbss#8]
После выхода Woocommerce 2.5 при использовании этой темы перестал работать скрипт AJAX обработки события добавления в корзину при нажатии кнопок на странице товаров.

Как оказалось, дело было в том, что в ссылках на добавление в корзину не было необходимого класса `ajax_add_to_cart`, по наличию которого активируется AJAX обработка.

Этот класс добавляется в файле [woocommerce/loop/add-to-cart.php](https://github.com/systemo-biz/wpbss/blob/master/woocommerce/loop/add-to-cart.php), для исправления проблемы можно просто скопировать измененный шаблон этого [файла из оригинального репозитория плагина](https://github.com/woothemes/woocommerce/blob/master/templates/loop/add-to-cart.php).

Могу оформить pull-request, если нужно.

**Comment by aiiddqd** [comment]
да было бы круто

**Comment by aiiddqd** [comment]
принял, спасибо :)

**Comment by apavliukov** [comment]
:thumbsup:
